export const All_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const All_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const All_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'